package contract

// Wire types exchanged between the control plane (internal/runner.agentRunner
// and the node-proxy client) and agenda-node (internal/node). Defined once here
// so both ends share a single definition, as with the gateway route contract.

// NodeJobRequest is the body of POST /v1/jobs. JobID is generated by the control
// plane and makes dispatch idempotent (a retried POST with the same id does not
// start a second command). Mode is "cmd" (Name+Args) or "shell" (Shell).
type NodeJobRequest struct {
	JobID string   `json:"job_id"`
	Dir   string   `json:"dir"`
	Env   []string `json:"env,omitempty"`
	Mode  string   `json:"mode"`
	Name  string   `json:"name,omitempty"`
	Args  []string `json:"args,omitempty"`
	Shell string   `json:"shell,omitempty"`
}

// NodeJobStatus is the response of GET /v1/jobs/:job_id. Output is populated
// when the job is terminal (success/failed).
type NodeJobStatus struct {
	Status   string `json:"status"` // running | success | failed
	ExitCode int    `json:"exit_code"`
	Output   string `json:"output"`
	Error    string `json:"error,omitempty"`
}

// Node job modes.
const (
	NodeJobModeCmd   = "cmd"
	NodeJobModeShell = "shell"
)

// NodeProxyRegisterRequest is the body of PUT /v1/proxy/:instance_name — it
// tells the node which local port an instance currently listens on.
type NodeProxyRegisterRequest struct {
	Port int `json:"port"`
}

// NodeHeartbeatRequest is the body of POST /api/v1/machines/:id/heartbeat.
type NodeHeartbeatRequest struct {
	Version string `json:"version"`
}
