package contract

// Wire types exchanged between the control plane (internal/runner.agentRunner
// and the node-proxy client) and agenda-node (internal/node). Defined once here
// so both ends share a single definition, as with the gateway route contract.

// HeaderNodeToken carries the per-machine agent token on control-plane→node
// requests and node→control-plane heartbeats.
const HeaderNodeToken = "X-Agenda-Node-Token"

// NodeJobRequest is the body of POST /v1/jobs. JobID is generated by the control
// plane and makes dispatch idempotent (a retried POST with the same id does not
// start a second command). Mode is "cmd" (Name+Args) or "shell" (Shell).
type NodeJobRequest struct {
	JobID string   `json:"job_id"`
	Dir   string   `json:"dir"`
	Env   []string `json:"env,omitempty"`
	Mode  string   `json:"mode"`
	Name  string   `json:"name,omitempty"`
	Args  []string `json:"args,omitempty"`
	Shell string   `json:"shell,omitempty"`
}

// NodeJobStatus is the response of GET /v1/jobs/:job_id. Output is populated
// when the job is terminal (success/failed).
type NodeJobStatus struct {
	Status   string `json:"status"` // running | success | failed
	ExitCode int    `json:"exit_code"`
	Output   string `json:"output"`
	Error    string `json:"error,omitempty"`
}

// Node job modes.
const (
	NodeJobModeCmd   = "cmd"
	NodeJobModeShell = "shell"
)

// NodeProxyRegisterRequest is the body of PUT /v1/proxy/:instance_name — it
// tells the node which local port an instance currently listens on.
type NodeProxyRegisterRequest struct {
	Port int `json:"port"`
}

// NodeHeartbeatRequest is the body of POST /api/v1/machines/:id/heartbeat.
type NodeHeartbeatRequest struct {
	Version string `json:"version"`
}

// AgendaContainerLogDir is the in-container log directory that sdk/go/log
// reads from AGENDA_LOG_DIR. The control plane's compose-override step
// (internal/pipeline) mounts <LocalPath>/logs onto this path on the deploy
// target's machine, and agenda-node's log-tail endpoint reads from the same
// path — defined once here so the two ends can't drift.
const AgendaContainerLogDir = "/var/log/agenda"

// AgendaContainerMetricsAddr is the fixed in-container listen address
// sdk/go/metric's AGENDA_METRICS_ADDR points at when a target has
// MetricsEnabled. The operator-chosen HOST port is separate
// (ApplicationEnvTarget.MetricsPort / the APP_METRICS_PORT env var passed to
// `docker compose up`, mirroring how APP_PORT already works) — this constant
// only fixes what the process inside the container binds to.
const AgendaContainerMetricsAddr = ":9464"

// Query params for GET /v1/metrics/:app/:instance.
const (
	NodeMetricsQueryPort = "port"
	NodeMetricsQueryPath = "path"
)

// DefaultMetricsPath is the HTTP path agenda-node fetches from
// 127.0.0.1:<port> when the "path" query param is omitted.
const DefaultMetricsPath = "/metrics"

// NodeLogFile is one matched on-disk log file in the response of
// GET /v1/logs/:app/:instance. Service is the AGENDA_SERVICE_NAME segment of
// the filename (empty for single-service apps that never set it).
type NodeLogFile struct {
	Service string   `json:"service"`
	File    string   `json:"file"`
	Lines   []string `json:"lines"`
}

// NodeLogsResponse is the body of GET /v1/logs/:app/:instance.
type NodeLogsResponse struct {
	App      string        `json:"app"`
	Instance string        `json:"instance"`
	Logs     []NodeLogFile `json:"logs"`
}
